hmcts/sscs-common

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CreateCcdCaseService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/ReadCcdCaseService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseService.java
the Retryable logic in the common is broken for the SearchCcdCaseService. That's the reason the test fails. Thanks, we have good coverage and this issue was caught by this test 
That test throws a RunTimeException correctly as it's coded in the mock. But the expectation is not met because the retry logic is not picked up and that's the reason you end up with a RunTimeException in the logs.
Here is the root cause of why the Retry is not picked up. It's an issue within the SpringBoot library actually. Search for the answer from nkharche.
https://stackoverflow.com/questions/38212471/springboot-retryable-not-retrying
That's exactly what we are experiencing, I can reproduce it locally and confirm it.
Now, I am working on the fix for this...
=> Fix retry and recovery logic

build.gradle
This will stop us having to update the build.gradle file every time we want
to release a new version.
=> Get the build number from git tag not hard coded in build.gradle.

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/utility/PhoneNumbersUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/utility/PhoneNumbersUtilTest.java
Check for mobile number, land line number and a valid uk mobile number.
There is a requirement to check for a valid uk mobile number in the notification service and case loaded.
There is an additional requirement (SSCS-4658) to send notifications to representatives when they give a valid mobile number - hence the need for a common component to handle this duplicated logic.
This PR uses the library @keefmarshall has identified to handle validation of phone numbers (https://github.com/googlei18n/libphonenumber)
=> SSCS-4658: Check for mobile number

src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java, src/main/java/uk/gov/hmcts/reform/sscs/utility/SurnameUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/utility/SurnameUtilTest.java
Moved the surname comparison logic out of a private method in the CcdService into a dedicated utility class and added logic to ignore (appointee) and its variants as per
https://tools.hmcts.net/jira/browse/SSCS-4820
=> Appointees to sign in with surname only

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
Added a number of new Event types so we can add COH events to CCD
and the case worker can see them in the timeline.
=> SSCS-4478 COH events in CCD

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
This was already in the spreadsheet but had not been added to sscs-common.
=> SSCS-5222 Added final decsion event to CCD events. 

src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/util/CaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-5232
When searching for a case with a surname and an appeal number, include appointee in the search.
Only merge into master branch once ticket SSCS-5232 has been QAed. Then merge and tag.
```
[ ] Yes
[x] No
```
=> Allow appointee surname search for TYA

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
These will be hidden from the caseworkers so cannot be seen in CCD. The 
user can upload to them but only when they submit all their evidence 
should it be copied across to the main place evidence is stored. Then the 
caseworker will be able to see it in CCD.
=> Added draft sscs documents and draft cor documents. 

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
This has been there a while but was only used by JUI. 
Fixed typo we were not setting the field value.
=> Added isCorDecision to the SscsCaseData.

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
Added states that exit interloc.
```
[ ] Yes
[X] No
```
=> SSCS-5812 Added states that exit interloc to Java

src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-6190
Fixing a bug where notifications are expecting a case id to be populated and its not
```
[ ] Yes
[x] No
```
=> Fixing a missing case id for the notifications service

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DirectionType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/StateTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
Add "Appeal to proceed" and "Provide information" as a "Direction Type" in the "Issue Direction" event
=> SSCS-6669 - add DirectionType

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7668
The business logic and validation for the manual upload route needs to know whether generate notice has been selected - this PR adds that attribute to SscsCaseData
```
[ ] Yes
[x] No
```
=> SSCS-7668 Adding writeFinalDecisionGenerateNotice attribute - needed for correct validation

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java, src/test/resources/updateFurtherEvidence.json
When serialising a `Callback<SscsCaseData>`, the `EventType` does not get serialised correctly.
It should be:
`"event_id":"directionIssued",`
rather than
`"event_id":"DIRECTION_ISSUED",`
=> SSCS-7730 - Correctly serialise EventType

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustBeInFutureValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustNotBeInFutureValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateYearMustBeInPast.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateYearMustBeInPastValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/ValidatorTestBase.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/documentlink/DocumentLinkMustBePdfValidatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustBeInFutureValidatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustNotBeInFutureValidatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateYearMustBeInPastValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-7834
* Adding field to SscsCaseData for jointPartyDob
* Adding validator for LocalDateYearMustBeInThePast, and annotating jointPartyDob with this.
* Adding unit test for LocalDateYearMustBeInThePastValidator, extending from ValidatorTestBase
* Adding missing unit tests for existing validators - extending each from ValidatorTestBase
* Correcting incorrect variable names in existing validators
* Added two test-scope dependencies for validation implementation.  These 2 dependencies are the ones used by the tribunals API and are only included for tests.
```
[ ] Yes
[x] No
```
=> Sscs 7834 joint party dob

src/main/java/uk/gov/hmcts/reform/sscs/utility/StringUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/utility/StringUtilsTest.java
https://tools.hmcts.net/jira/browse/SSCS-8034
* Moving StringUtils from tribunals to common so it can be used by bulk loader
```
[ ] Yes
[x] No
```
=> SSCS-8034 Moving StringUtils from tribunals to common so it can be used by bulk loader

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7515
Adding wca appeal and support group only appeal fields ( required by both ESA and UC)
```
[ ] Yes
[x] No
```
=> SSCS-7515 Adding wca appeal and support group only appeal fields

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
SSCS-8351 - Notification - Adjournment notice Welsh translations
This PR adds a new event ISSUE_ADJOURNMENT_NOTICE_WELSH that when triggered will send the welsh Adjournment notice
=> SSCS-8351 - Notification - Adjournment notice Welsh translations

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
At the moment we have added annotations within our case data model which perform various forms of validation which is triggered when mid event callbacks are used, this has caused a problem before and ticket SSCS-9069 resolve it for the direction due date, however there are other forms of validation which will need to be removed and added against the correct events.
The annotation that needs to be removed is @LocalDateMustBeInFuture, which affects the following fields:
- adjournCaseDirectionsDueDate
- notListableDueDate
- updateNotListableDueDate
And affects the following events:
- adjournCase
- notListable
- updateNotListable
This ticket is to only look at the adjournCase (Write adjournment notice) event
=> SSCS-9094 remove annotation validation

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AudioVideoEvidenceDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
add original sender to audioVideoEvidence
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9677](url)
=> SSCS-9677-add original sender to audioVideoEvidence

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OverrideSchedulingListingFields.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SchedulingAndListingFields.java
https://tools.hmcts.net/jira/browse/SSCS-10559
- Adding new class for overrideSchedulingListingFields - which contains the first field for override duration
- SchedulingAndListingFields class now contians OverrideSchedulingListingFields overrideSchedulingListingFields
```
[ ] Yes
[x] No
```
=> feat/SSCS-10559: Adding overrideSchedulingListingFields

src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java, src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoaderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10332
Changes to common project for VenueService and VenueDataLoader to retain mapping of RPC to venues as well as allow retrieval of EpimsIds for all venues under a particular RPC name.
```
[ ] Yes
[x] No
```
=> SSCS-10332 - Ability to book hearings for 'paper' cases to any venue within the same region as the RPC

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
https://tools.hmcts.net/jira/browse/SSCS-10177
A new value 'Hearing Date Issued' should be added to the list of values available for the attribute 'FTA State' .
```
[ ] Yes
[x ] No
```
=> add new dwp state hearing date issued

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-769
CVE-2023-24998
There's no patch for the direct dependency, so **added a new dependency** for commons-fileupload@1.5
CVE-2023-2976, CVE-2020-8908
There is an existing dependency for com.google.guava:guava:32.1.1-jre and version 30.1.1-jre is only used by the checkstyle plugin. Plugin 'checkstyle' is a core Gradle plugin, which cannot be specified with a version number.  Such plugins are versioned as part of Gradle. Gradle 8.6 (latest version) uses com.puppycrawl.tools:checkstyle:9.3 (and com.google.guava:guava:31.0.1-jre), so upgrading gradle doesn't solve the CVE.
Could add a new dependency of com.puppycrawl.tools:checkstyle:8.45.1 to versrion 10.12.1 to fix CVE but that's a major, so **suppressing for now**.
CVE-2023-5072
**Patched** …
=> CVE minor or patch upgrade

build.gradle
There is a mandatory dependency check plugin update: https://github.com/jeremylong/DependencyCheck?tab=readme-ov-file#mandatory-upgrade-notice that will allow the NVD to block calls from the older client
Bumped dependency check to 10.0.2
=> Bump dependency check plugin to 10.0.2

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
A fix to factor in the event of when a case is being created via MCC and mid event handler is called. It saves the dropdown selected benefitType to the descriptionSelection so it's passing as false for isIbcCase when it should be true.
=> Fix is ibc case

src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java, src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelMemberComposition.java, src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/DefaultPanelComposition.java, src/main/java/uk/gov/hmcts/reform/sscs/reference/data/service/PanelCompositionService.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelMemberCompositionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/reference/data/model/DefaultPanelCompositionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/reference/data/service/PanelCompositionServiceTest.java
See [SSCSCI-1945](https://tools.hmcts.net/jira/browse/SSCSCI-1945)
- simplify and consolidate panelComposition calculation logic
- reset panelComposition when issueCode/specialismsCount change
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> SSCSCI-1945: consolidate panelComposition calculation logic and reset when stale
