hmcts/sscs-common

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/SscsCaseDataUtils.java
- Remove non CCD events from EventType object
- Remove notification type from SscsCaseData object
> Remove non CCD events from EventType object

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscriptions.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/util/CaseDataUtils.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
Add appeal created on subscription
> SSCS-4614 - appointee tya number generation

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
JUI will add thr tribunals final decision into the decision notes field.
As this is a new field it needs to be added to sscs-common so we can use
it.
> SSCS-3973 Show tribunal final decision

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/Callback.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/Deserializer.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializer.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/exception/RequiredFieldMissingException.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/callback/CallbackTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/resources/appealReceivedCallback.json
https://tools.hmcts.net/jira/browse/SSCS-5203
Add deserialiser for SSCS case objects when callback requests are received from CCD
```
[ ] Yes
[ x] No
```
> SSCS-5203 SSCS case deserialiser for CCD callbacks

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CreateCcdCaseService.java
> SSCS-5162 internal server error, propagating message to front end level

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
This has been there a while but was only used by JUI.
> Added isCorDecision to the SscsCaseData

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-5219
> Bump java logging version

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
> SSCS-5104 Add eventType for DRAFT appeals

- build.gradle
This reverts commit 66309db1ee105c4b893bb706798123e624ee840b.
```
[ ] Yes
[ ] No
```
> Revert "Bump java logging version (#115)"

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Bundle.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> Sscs 4299 stitching and bundling

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
> SSCS-4517 Regenerate SSCS1 pdf functionality

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
Added relistingReason field
https://tools.hmcts.net/jira/browse/SSCS-5223
```
[ ] Yes
[X] No
```
> SSCS-5223 Added relistingReason field to SscsCaseData

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
Add a new Event Type for `draftArchived`.
> SSCS-5105 - Add a new EventType for `draftArchived`.

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Address.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
> add new postcode look up fields to be stored in CCD

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscription.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SubscriptionTest.java
> fix code to take into account empty values

- README.md
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
https://tools.hmcts.net/jira/browse/SSCS-5518
Implement caching of idam tokens
```
[X] Yes
[ ] No
```
> SSCS-5518 - Implement caching of idam tokens

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
Added interlocSecondaryState to CCD domain object
https://tools.hmcts.net/jira/browse/SSCS-5812
> SSCS-5812 Added interlocSecondaryState field to CCD domain object

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> add secondary state to the ccd case data model

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
Added outcome field to ccd object
> SSCS-5972 Added outcome field to ccd object

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
Added UPLOAD_FURTHER_EVIDENCE event to ccd domain objects
> SSCS-5812 Added UPLOAD_FURTHER_EVIDENCE_EVENT

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
> Add new event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingTypeTest.java
> add COR HearingType enum

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscription.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SubscriptionTest.java
whether user is or not subscribed
```
[ ] Yes
[ ] No
```
> take into account the wantSmsNotification property to work out

- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-4067
Import idam request logging
```
[ ] Yes
[X] No
```
> SSCS-4067 - improve idam request logging

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/CallbackType.java
> add one more enum for the submitted callback

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/ReadCcdCaseService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-4157
> Additional logging around IDAM requests

- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-4157
> Reinstate exception part of log message

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> add new field to the sscsCaseData type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
> SSCS-5227 Issue further evidence 

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
Add panel members fields to CCD object and remove old online panel
as it is not used.
https://tools.hmcts.net/jira/browse/SSCS-6242
```
[ ] Yes
[X] No
```
> SSCS-6242 Add panel members fields to CCD object

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
Add appendix to an sscs document
Will be available in v91 of the CCD definition
> SSCS-6023 - Add appendix to an sscs document

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> SSCS-6382 add new field to case data to store the dwp regional centre

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-6199
Added interloc referral date
```
[ ] Yes
[x] No
```
> Added interloc referral date

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Note.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/NoteDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/NotePad.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/resources/adminAppealWithdrawnCallback.json
https://tools.hmcts.net/jira/browse/SSCS-6304
> SSCS-6304 withdrawn appeal

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> Add created in gaps from field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
> SSCS-6381 - Ready to list Event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpResponseDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
Dwp response cleared - because its not in the data model
> SSCS-6699 - Dwp response cleared

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-6759
> add new send to admin event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-6305
Added DWP_DIRECTION_RESPONSE event
```
[ ] Yes
[X] No
```
> Added DWP_DIRECTION_RESPONSE event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
Add a new event `validSendToInterloc`
> SSCS-6758 - valid send to interloc event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-6520
> SSCS-6520 add dwpChallengeValidity

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> SSCS-6380 Fields added for response reviewed callbacks

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-6938
> SSCS-6938 add new event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-6786
> SSCS-6786 Handle empty doc types when finding latest doc

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ExtensionNextEvent.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-6570
> SSCS-6570 Extension next event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-6798
added event
```
[] Yes
[X] No
```
> Sscs 6798 set can review

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EvidenceReceived.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EvidenceReceivedInformation.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EvidenceReceivedInformationDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Panel.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-6836
> SSCS-6836 Add missing fields to the data model

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-6993
> SSCS-6993 Resend to DWP event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
https://tools.hmcts.net/jira/browse/SSCS-6846
> SSCS-6846 Change directions notice

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-6959
> SSCS-6959 Add admin send to dwp event to model

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DynamicList.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ExtensionNextEvent.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/resources/reissueFurtherEvidence/reissueFurtherEvidenceCallbackWithDynamicListAsPerAboutToStartCallback.json
- src/test/resources/reissueFurtherEvidence/reissueFurtherEvidenceCallbackWithDynamicListAsPerMiddleEventCallback.json
- src/test/resources/reissueFurtherEvidence/reissueFurtherEvidenceCallbackWithEmptyDynamicList.json
> SSCS-7012 Change Extension decision to dynamic list

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> Sscs 7014 hide options grant deny

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-6979
> SSCS-6979 Response required field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7056
> SSCS-7056 interlocInformationReceivedActionFurtherEvidence event

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
> SSCS-7047 SYA – OpenID connect – Validate the IDAM token that is return

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7088
> SSCS-7088 Notification sent event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
https://tools.hmcts.net/jira/browse/SSCS-7090
> SSCS-7090-Set-new-case-dwp-state

- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
> SSCS-6809 Changes to support new PIP AE office added by DWP

- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7148
> SSCS-7148 Get DWP regional center by benefit type and office

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleFolder.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleFolderDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleSubfolder.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BundleSubfolderDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpResponseDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocument.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-7120
> Sscs 7120 bundle config

- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamTokens.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserDetails.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
> SSCS-6850 Associate the submitted case with the IDAM ID (S&R)

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-7308
> SSCS-7308 Change sort order when selecting latest document for document type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/Callback.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/callback/CallbackTest.java
https://tools.hmcts.net/jira/browse/SSCS-7295
> SSCS-7295 Add warning message to callback

- src/main/resources/reference-data/dwpAddresses.json
https://tools.hmcts.net/jira/browse/SSCS-7301
> SSCS-7301 change gaps code to PIP AE

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscription.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/util/CaseDataUtils.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamTokens.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserDetails.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
> SSCS-7147 Timestamp of last logged into MYA in CCD UI

- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
> SSCS-7299 IDAM - Review

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/MrnDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
https://tools.hmcts.net/jira/browse/SSCS-7316
> SSCS-7316 Update closed offices

- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
> SSCS-7375: SYA/Bulk scan – Remove PIP 10

- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7389
> SSCS-7389 Find PIP AE office without brackets

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscription.java
https://tools.hmcts.net/jira/browse/SSCS-7256
> SSCS-7256 Check for empty subscription

- src/main/resources/reference-data/dwpAddresses.json
https://tools.hmcts.net/jira/browse/SSCS-7481
> SSCS-7481 Sheffield DRT changes for Worthing and Milton Keynes

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-7497
Addition of new EventType for ISSUE_DECISION.
Addition of 3 fields for pip type of award questions  in SscsCaseData
```
[ ] Yes
[ x] No
```
> Sscs 7494 decision notices pip type of award questions

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7498
Adding pipDecisionNotice startDate, endDateType and endDate fields
```
[ ] Yes
[x ] No
```
> SSCS-7498 Adding pipDecisionNotice startDate, endDateType and endDate

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-7497
Changing event type and event property names in line with change from "decisionNotice" to "writeFinalDecision"
```
[ ] Yes
[x ] No
```
> SSCS-7497 Changing event type and event property names in line with change from "decisionNotice" to "writeFinalDecision"

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/resources/reference-data/decision-notice-questions.json
- src/main/resources/reference-data/decision-notice-questions.txt
https://tools.hmcts.net/jira/browse/SSCS-7539
https://tools.hmcts.net/jira/browse/SSCS-7500
* Adding fields for SSCS-7500 to the Java model and adding the required questions
for SSCS-7500 to the decision-notice-questions.txt file
```
[ ] Yes
[x ] No
```
> Sscs 7539 store decision question json spike

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7536
*  Adding decision date to Java SscsCaseData model
```
[ ] Yes
[ x] No
```
> Sscs 7536 decision notices decison date

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7536
* SSCS-7536 Renaming decisionDate to dateOfDecision for cleaner variable names
```
[ ] Yes
[x ] No
```
> SSCS-7536 Renaming decisionDate to dateOfDecision for cleaner variable names

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7504
* Adding pipWriteFinalDecisionReasonsForDecision to SscsCaseData
```
[ ] Yes
[ x] No
```
> SSCS-7505 Adding pipWriteFinalDecisionReasonsForDecision to SscsCaseData

- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
Strip out non used parameters.
```
[ ] Yes
[ ] No
```
> Sscs 7571 tidy

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7617
> SSCS-7617 Remove writeFinalDecisionGenerateNotice field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7666
> SSCS-7666 Add generated date for decision notice

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CollectionItem.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7637
https://tools.hmcts.net/jira/browse/SSCS-7697
* Adding attributes for non-descriptor flow
* Changing reasons to a collection field
* Adding "anythingElse" field to both flows.
```
[ ] Yes
[ x] No
```
> Sscs 7637 sscs 7697 non descriptor flow

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
SSCS-7384 - Remove a case link
Added a new event ** removeLinkForCase**
> SSCS-7384 - Remove a Case Link

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-7729
```
[ ] Yes
[ ] No
```
> SSCS-7729 Idam Java client upgrade with logging

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7485
> SSCS-7485 Reissue document event

- .github/renovate.json
Use renovate for gradle wrapper upgrades
> use renovate for gradle wrapper upgrade PRs

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7728
Removing writeFinalDecisionDocumentDateAdded and writeFinalDecisionDocumentFileName fields
```
[ ] Yes
[x] No
```
> SSCS-7728 PIP DN tidy up actions

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7624
* Adding adjourn case event type
```
[ ] Yes
[ x] No
```
> SSCS-7624 Adding adjourn case event type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7740
> SSCS-7740 Add pcqId to case data

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7625
*. Adding adjournCaseGenerateNotice and adjournCaseTypeOfHearing attributes to SscsCaseData 
```
[ ] Yes
[x] No
```
> SSCS-7625 Adding adjournCaseGenerateNotice and adjournCaseTypeOfHearing

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7626
* Adding fields for the "can case be listed right away" pages
```
[ ] Yes
[x] No
```
> SSCS-7626 Adding fields for the "can case be listed right away" pages

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7628
* Adding adjournCasePanelMembersExcluded
```
[ ] Yes
[x] No
```
> SSCS-7628 Adding adjournCasePanelMembersExcluded - PR # 1

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7629
* Adding panel members names
```
[ ] Yes
[x] No
```
> Sscs 7629 panel members names - PR # 2 - builds on PR # 1

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7631
* Adding fields required for the "when should next hearing be" page
```
[ ] Yes
[x] No
```
> SSCS-7631 Adding fields required for the "when should next hearing be" page

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7691
* Adding next hearing duration fields
```
[ ] Yes
[x] No
```
> SSCS-7691 Adding next hearing duration fields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7632
https://tools.hmcts.net/jira/browse/SSCS-7638
* Adding reasons and anything else attributes to SscsCaseData
```
[ ] Yes
[x] No
```
> SSCS-7632 SSCS-7638 Adding reasons and anything else attributes to SscsCaseData

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7639
* Adding adjournCasePreviewDocument to SscsCaseData
```
[ ] Yes
[x] No
```
> SSCS-7639 Adding adjournCasePreviewDocument

- src/main/java/uk/gov/hmcts/reform/sscs/model/VenueDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
https://tools.hmcts.net/jira/browse/SSCS-7639
* Migrating VenueDataLoader from case-loader to common
```
[ ] Yes
[x] No
```
> SSCS-7639 Migrating venue data loader from case-loader to common

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7639
Adding adjournCaseGeneratedDate to case data
```
[ ] Yes
[x] No
```
> SSCS-7639 Adding adjourn case generated date

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7605
> SSCS-7605 Not listable event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7607
> SSCS-7607 Not listable due date field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7609
> SSCS-7609 Update not listable event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7610
> SSCS-7610 Add updateNotListableDirectionsFulfilled field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7611
> SSCS-7611 Update not listable interloc fields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7665
> SSCS-7665 Issue adjournment notice

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustBeInFuture.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustBeInFutureValidator.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustNotBeInFuture.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateMustNotBeInFutureValidator.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/StateTest.java
https://tools.hmcts.net/jira/browse/SSCS-7612
> SSCS-7612 Update not listable due date

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/StateTest.java
https://tools.hmcts.net/jira/browse/SSCS-7038
Remove Outcome State from SSCS-Common
```
[ ] Yes
[X] No
```
> SSCS-7038 Remove Outccome State

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/StateTest.java
SSCS-7039 - CCD UI - Deprecate 'Test Create Case' state
> SSCS-7039 - CCD UI - Deprecate 'Test Create Case' state

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/StateTest.java
SSCS-7040 - CCD UI - Deprecate 'Void application' state
> SSCS-7040 - CCD UI - Deprecate 'Void application' state

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/documentlink/DocumentLinkMustBePdf.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/documentlink/DocumentLinkMustBePdfValidator.java
https://tools.hmcts.net/jira/browse/SSCS-7855
SSCS-7855-Adding pdf validators, and configuring SscsCaseData with pdf and adjourn case directions due date validation
```
[ ] Yes
[x] No
```
> SSCS-7855-Adding pdf validators, and configuring SscsCaseData with pdf and adjourn case directions due date validation

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/StateTest.java
https://tools.hmcts.net/jira/browse/SSCS-7037
Remove pendingAppeal state
```
[ ] Yes
[X] No
```
> SSCS-7037 Remove pendingAppeal state

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ElementDisputed.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ElementDisputedDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7829
> SSCS-7829 Elements and issues

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7828
* Adding jointParty property to SscsCaseData
```
[ ] Yes
[x] No
```
> Sscs 7828 is joint party on case

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7833
* Adding joint party name fields to SscsCaseData
```
[ ] Yes
[x] No
```
> Sscs 7828 joint party name

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/nino/NationalInsuranceNumber.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/nino/NationalInsuranceNumberValidator.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/nino/NationalInsuranceNumberValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-7835
* Adding jointPartyNino to SscsCaseData and NationalInsuranceNumberValidator
```
[ ] Yes
[x] No
```
> Sscs 7835 adding nino and validator

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/WLA-664
```
[ ] Yes
[ X] No
```
> WLA-664: added update welsh preference event type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Address.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/Postcode.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/PostcodeValidator.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/groups/UniversalCreditValidationGroup.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/string/StringNoSpecialCharacters.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/validation/string/StringNoSpecialCharactersValidator.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/NonUniversalCreditAddressCanContainSpecialCharactersTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/NonUniversalCreditAddressPostcodeCanBeInvalidTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/PostcodeValidatorTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/UniversalCreditAddressMustNotContainSpecialCharactersTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/address/UniversalCreditAddressPostcodeMustBeValidTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/sscscasedata/JointPartyAddressAndAppellantAddressValidationTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/string/StringNoSpecialCharactersValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-7836
https://tools.hmcts.net/jira/browse/SSCS-7837
* Adding joint party address, same as appellant address flag, and validation
```
[ ] Yes
[x] No
```
> Sscs 7836 sscs 7837 Adding joint party address, same as appellant address flag, and validation

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> SSCS-7345 Add IsScottishCase to case data

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Identity.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/NameNoTitle.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/NameNoTitleTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/identity/NonUniversalCreditIdentityCanBeInvalidTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/identity/UniversalCreditIdentityMustBeValidTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/sscscasedata/JointPartyIdentityAndAppellantIdentityValidationTest.java
https://tools.hmcts.net/jira/browse/SSCS-7989
Migrating name and identity properties to complex types
```
[ ] Yes
[x] No
```
> Sscs 7989 name identity complex types

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
SSCS-7309 - Set 'Previous State' field when case moves to dormant
> SSCS-7309 - Set 'Previous State' field when case moves to dormant

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8049
https://tools.hmcts.net/jira/browse/SSCS-7935
Adding Adding dwpUploadResponseDynamicBenefitType DynamicList
```
[ ] Yes
[x] No
```
> SSCS-7935 SSCS-8049 Adding dwpUploadResponseDynamicBenefitType DynamicList

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidator.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsValidationException.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsWrapper.java
- src/main/resources/schema/sscs-robotics.json
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidatorTest.java
- src/test/resources/schema/valid_robotics_agreed.json
> Add Robotics Json Mapper and Validator

- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidator.java
SSCS-7860
fixing the move of robotics to common with a default value for schema to fix notifications
```
[ ] Yes
[x] No
```
> set a default for schema

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ReinstatementOutcome.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
SSCS-7806 - Processing documents for reinstatement requests
> SSCS-7806 - Processing documents for reinstatement requests

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscriptions.java
https://tools.hmcts.net/jira/browse/SSCS-7977
```
[ ] Yes
[x] No
```
> SSCS-7977 add joint part subs

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Appeal.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingSubtype.java
https://tools.hmcts.net/jira/browse/SSCS-7930
> SSCS-7930 Universal credit bulk scan fields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Subscriptions.java
SSCS-7977
```
[ ] Yes
[x] No
```
> added assignment

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
WLA-710
Event added - Welsh – mark docs for trans
```
[ ] Yes
[ X] No
```
> WLA-710: Welsh – mark docs for trans

- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/resources/schema/sscs-robotics.json
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
https://tools.hmcts.net/jira/browse/SSCS-7860
Moved code from evidence share
```
[ ] Yes
[x] No
```
> SSCS 7860 Moved code from evidence share

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> Wla 698 interloc welsh

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
> SSCS-7812 Add DWP Reinstatement status

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-8126
Adding ADMIN_RESTORE_CASES event
```
[ ] Yes
[x] No
```
> SSCS-8126 Adding ADMIN_RESTORE_CASES event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8108
> Additional directions list for adjournments

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AdjournCaseTime.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8107
> SSCS-8107 Adjourn case time changes

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/ScannedDocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/JointPartyName.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/RequestOutcome.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7998
> SSCS-7998 confidential request

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-7999
Adding REVIEW_CONFIDENTIALITY_REQUEST event
```
[ ] Yes
[x] No
```
> SSCS-7999 Adding REVIEW_CONFIDENTIALITY_REQUEST event type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/util/CaseDataUtils.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/resources/schema/sscs-robotics.json
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
https://tools.hmcts.net/jira/browse/SSCS-8198
> SSCS-8198 Add hearing telephone and video email fields to robotics

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8204
Joint party login to mya
```
[ ] Yes
[x] No
```
> SSCS 8204 Added joint party

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DatedRequestOutcome.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/RequestOutcome.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7998
* Adding DwpState for confidentiality action required
```
[ ] Yes
[x] No
```
> Sscs 7999 review confidentiality request

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/RequestOutcome.java
https://tools.hmcts.net/jira/browse/SSCS-7999
Removing not set from RequestOutcome
```
[ ] Yes
[x] No
```
> SSCS-7999 Removing not set from RequestOutcome

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DirectionType.java
> SSCS-7810 Add Direction Type Reinstatement status

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8204
```
[ ] Yes
[x] No
```
> Added feature flag

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8235
```
[ ] Yes
[ ] No
```
> Documents tab - JP uploading evidence to MYA

- src/main/resources/reference-data/esa-decision-notice-questions.txt
> SSCS-7516 schedule 2 scores

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-7994
```
[ ] Yes
[x] No
```
> sscs-7994 added eventtype

- src/main/resources/reference-data/esa-decision-notice-questions.txt
https://tools.hmcts.net/jira/browse/SSCS-7515
https://tools.hmcts.net/jira/browse/SSCS-7516
Fixing typos found by manual testing
```
[ ] Yes
[x] No
```
> Sscs 7515 esa schedule 2 activities fix

- src/main/resources/reference-data/esa-decision-notice-questions.txt
- src/main/resources/reference-data/pip-decision-notice-questions.txt
https://tools.hmcts.net/jira/browse/SSCS-7566
* Adding display order to pip and esa fixed lists
```
[ ] Yes
[x] No
```
> SSCS-7566 Adding display order to pip and esa fixed lists

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8008
> SSCS-8008 Summary of outcome show condition

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-8359
> SSCS-8359 Amend elements issues event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7578
Adding showSchedule3ActivitiesPage field to workaround not being able to combine AND and OR conditions
```
[ ] Yes
[ ] No
```
> SSCS-7578 Adding showSchedule3ActivitiesPage field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-7578
Adding helper methods for Schedule3 and Regulation 35
```
[ ] Yes
[x] No
```
> SSCS-7578 Adding helper methods for Schedule3 and Regulation 35

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsEsaCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-8385
* Moving ESA fields to a separate nested domain object annotated with @JsonUnwrapped.
* Removing all-args constructor
* Adding necessary annotations to properties that had non-default annotations previously in the constructor
* Adding @JsonProperty to all properties that had custom @JsonIgnore methods added.
```
[ ] Yes
[x] No
```
> Sscs 8385 lombok parameter issue fix v5

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsQueryBuilder.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsQueryBuilderTest.java
> SSCS-8383: Caseloader – Updating the wrong case

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsEsaCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7578
* Moving esa specific fields into SscsEsaCaseData and generic fields up to SscsCaseData
```
[ ] Yes
[x] No
```
> SSCS-7578 Moving esa specific fields into SscsEsaCaseData and generic fields up to SscsCaseData

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsEsaCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8048
Moving wcaAppeal field to SscsEsaCaseData
```
[ ] Yes
[x] No
```
> SSCS-8048 Moving wca appeal field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8309
> Sscs 8309 uc reassess award

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsEsaCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsUcCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/YesNo.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/YesNoTest.java
> Sscs-8048 uc fields 2

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DocumentLink.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> SSCS-7789 Add Dwp Documents to case data

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Outcome.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8328
> SSCS-8328 Abate case event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8334
> SSCS-8334 Provide appointee details event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8326
> SSCS-8326 Record death of appellant event

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidator.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsValidationException.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidatorTest.java
> SSCS-8106 Json Schema Validator

- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
> SSCS-8424 - Remove UC flag

- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/IdamServiceTest.java
> SSCS-8038: Caseloader – Retry attempt to obtain IDAM token

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8499
> SSCS-8499 Record date of appellant death

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
SSCS-8287 - Add/Remove UCB flag
> SSCS-8287 - Add/Remove UCB flag

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8499
> Appellant death date validation

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DwpDocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/YesNo.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/YesNoTest.java
- src/test/resources/adminAppealWithdrawnCallback.json
- src/test/resources/updateFurtherEvidence.json
> SSCS-8286 - UCB Document

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8284
```
[ ] Yes
[ ] No
```
> Sscs 8284: Add event for "Review PHME request"

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8283
```
[ ] Yes
[x] No
```
> sscs-8283 Added new fields for edited evidence

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterService.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterServiceTest.java
SSCS-8503 - Add processingVenue field
> SSCS-8503 - Add processingVenue field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
added isSaveAndReturn boolean to SscsCaseData
Jira link: [https://tools.hmcts.net/jira/browse/SSCS-7682](url)
> added isSaveAndReturn boolean to SscsCaseData

- src/main/resources/reference-data/esa-decision-notice-questions.txt
- src/main/resources/reference-data/uc-decision-notice-questions.txt
https://tools.hmcts.net/jira/browse/SSCS-8536 and https://tools.hmcts.net/jira/browse/SSCS-8537
> SSCS-8536 and SSCS-8537 minor changes to decision notice content

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-8472
> SSCS-8472 Death of appellant actioned event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidator.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidatorTest.java
> SSCS-8530: Robotics - send to robotics error

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DwpDocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8525
> SSCS-8525 Appendix 12 document

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DwpDocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
Changes for updateReasonableAdjustmentsOutstanding flag
> Changes for updateReasonableAdjustmentsOutstanding flag

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8496
Adding annotations to pipSscsCaseData for pip fields to mirror the annotations for ESA and UC
```
[ ] Yes
[x] No
```
> SSCS-8385 Adding annotations to pipSscsCaseData

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8458
```
[ ] Yes
[x] No
```
> sscs-8458-add-edited-event

- src/main/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterService.java
https://tools.hmcts.net/jira/browse/SSCS-8573
```
[ ] Yes
[ ] No
```
> SSCS-8573: White list scottish postcode for local testing

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ScannedDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-8116
> SSCS-8116 Edited document url

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DraftSscsDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DraftSscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
SSCS-7816 - CCD UI – Disconnect uploadFurtherEvidence from sscsDocument
> SSCS-7816 - CCD UI – Disconnect uploadFurtherEvidence from sscsDocument

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8606
> SSCS-8606 Death of appellant flag

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
SSCS-8593 Issue Edited Docs to all Parties
> SSCS-8593 Issue Edited Docs to all Parties

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsEsaCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsUcCaseData.java
> Sscs 8568 removing lcwa appeal

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DwpDocumentType.java
https://tools.hmcts.net/jira/browse/SSCS-8600
> SSCS-8600 Add dwp response docs to DwpDocumentType

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-8601
> Add edited document to dwp docs

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-8602
> SSCS-8602 Move dwpEditedEvidenceReason to dwp doc collection

- build.gradle
SSCS-8684- Upgrade Idam client
> SSCS-8684- Upgrade Idam client

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserDetails.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/UserDetailsTest.java
SSCS-8734 exclude evidence
based off branch 8733-Process-Audio-Video-Evidence #734
> SSCS-8734 exclude evidence

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/resources/decisionAppealToProceed.json
SSCS-8750 : DwpDocument sorting
> SSCS-8750 : DwpDocument sorting

- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserRole.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/UserDetailsTest.java
> SSCS-8813 : Super user access

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/UserRole.java
- src/test/java/uk/gov/hmcts/reform/sscs/idam/UserDetailsTest.java
Added processAudioVideo event and processAudioVideoAction dynamic list
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8733](url)
> Added processAudioVideo event and processAudioVideoAction dynamic list

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
https://tools.hmcts.net/jira/browse/SSCS-8753
> SSCS-8753 RIP1 bundle document

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> SSCS-8740 - Add Note field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DwpDocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AudioVideoEvidenceDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/UploadParty.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/UploadPartyTest.java
https://tools.hmcts.net/jira/browse/SSCS-8741
> SSCS-8741 Include audio video evidence

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTypeEnum.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
SSCS-8760 - DWP offices for DLA benefit type
> SSCS-8760 - DWP offices for DLA benefit type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-8829
> SSCS-8829:Add Welsh flag - RIP1 Document

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
SSCS-8752 - Issue Audio/Video Notice
_New event_ **processAudioVideoWelsh**, that will be triggered by the code when it sees a _new documentType_ of **audioVideoNotice**
> SSCS-8752 - Issue Audio/Video Notice

- src/main/java/uk/gov/hmcts/reform/sscs/service/CaseCodeService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CaseCodeServiceTest.java
set DLA benefit code to 037
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8835](url)
> set DLA benefit code to 037

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/MultiBundleConfig.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8851
> Sscs 8851 multi bundle integration test

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-8827
> SSCS-8827 Single case to draft events

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-8861
> Sscs 8861 rip1 document translation

- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
SSCS-8968 - Robotics – PIP AE isn't showing correctly for DwpOriginatingOffice and DwpPresentingOffice
> SSCS-8968 - Robotics – PIP AE isn't showing correctly for DwpOriginatingOffice and DwpPresentingOffice

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/NoteDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8770
Note field
```
[ ] Yes
[x] No
```
> Sscs 8770 new note field

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
SSCS-8857- No Welsh translation for decision notice
> SSCS-8857- No Welsh translation for decision notice

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/CaseCodeService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CaseCodeServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8892
> SSCS-8892 Map Carer's Allowance to 070 benefit code

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTypeEnum.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8894
```
[ ] Yes
[ ] No
```
> SSCS-8894:Carer's Allowance - Airlookup, DWP addresses & Robot Configuration

- .github/workflows/jitpack_build.yml
- jitpack.yml
- Add workflow to force jitpack to build when a tag is pushed.
> DTSPO-1792 - force jitpack to build when code is tagged

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/NoteDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
Sscs 8771 simplify adding notes
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8771](url)
> Sscs 8771 simplify adding notes

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTypeEnum.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
> Revert "SSCS-8894:Carer's Allowance - Airlookup, DWP addresses & Robot Configuration"

- build.gradle
- removed duplicate commons-lang3
- renamed group
> SSCS-9043 - build common libraries

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsFurtherEvidenceDocDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9017
> SSCS-9017 change lombok to data

- .github/workflows/jitpack_build.yml
Improve reliability of Jitpack script
```
[ ] Yes
[x] No
```
> Improve Jitpack script

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
> SSCS-8855 Resized Document Link

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTypeEnum.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8894
https://tools.hmcts.net/jira/browse/SSCS-9037
```
[x] Yes
[ ] No
```
> SSCS-8894: Carer's Allowance - Airlookup, DWP addresses & Robot Configuration

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9069
> SSCS-9069 Remove direction due date validation

- .github/workflows/jitpack_build.yml
- Up the amount of retries to 6 and improve reliability 
```
[ ] Yes
[x] No
```
> Up the amount of retries to 6 and improve reliability

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
SSCS-9050 - DLA - Update Welsh SSCS1 Form
> SSCS-9050 - DLA - Update Welsh SSCS1 Form

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
https://tools.hmcts.net/jira/browse/SSCS-8766
> SSCS-8766 Attendance Allowance benefit type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
> SSCS-8995 - Hmcts evidence

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AudioVideoEvidenceDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9015
```
[ ] Yes
[ ] No
```
> SSCS-9015:Investigate how to play mp3 and mp4 videos in browser from CCD 

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
SSCS-8901 - Attendance Allowance - Map Caseloader to Attendance Allowance Benefit Code
> SSCS-8901 - Attendance Allowance - Map Caseloader to Attendance Allowance Benefit Code

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
added generate coversheet event to EventType
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-8966](url)
> added generate coversheet event to EventType

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
added hasUnprocessedAudioVideoEvidence flag to SscsCaseData
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9096](url)
> added hasUnprocessedAudioVideoEvidence flag to SscsCaseData

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
https://tools.hmcts.net/jira/browse/SSCS-9112
> SSCS-9112 Decision actioned dwp state

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/util/CaseDataUtils.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8879
Adding DLA codes
```
[ ] Yes
[x] No
```
> sscs 8879 added dla code

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
https://tools.hmcts.net/jira/browse/SSCS-8906
> SSCS-8780 Add Bereavement Benefit

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
Moving to jitpack and removing bintray
```
[ ] Yes
[x] No
```
> sscs 9066 moved to jitpack and removed bintray

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8870
> SSCS-8870:CCD UI – Implement DWP due date field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-8920
> SSCS-8920 showWorkCapabilityAssessmentPage field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelComposition.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelCompositionTest.java
SSCS-9154 - Carer's Allowance - Panel List for Notification Content
> SSCS-9154 - Carer's Allowance - Panel List for Notification Content

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
added elementsDisputedLimited list
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9124](url)
> added elementsDisputedLimited list

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCS-9165
> SSCS-9165 Playback audio video evidence event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
https://tools.hmcts.net/jira/browse/SSCS-9117
> SSCS-9117 Remove dwp confidential state

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9079
```
[ ] Yes
[ ] No
```
> SSCS-9079: Carer's Allowance (SYA) - Update the FL_dwpRegionalCentre list in CCD

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
https://tools.hmcts.net/jira/browse/SSCS-8933
```
[ ] Yes
[ ] No
```
> SSCS-8933: IIDB - Airlookup, DWP addresses & Robot Configuration

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/AirlookupBenefitToVenue.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8906
> SSCS-8906 Bereavement benefit dwp mappings

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/AirlookupBenefitToVenue.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8808
https://tools.hmcts.net/jira/browse/SSCS-8933
```
[ ] Yes
[ ] No
```
> SSCS-8808:IIDB (SYA) - Allow Industrial Injuries Disablement Benefit Submission

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelComposition.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/AirlookupBenefitToVenue.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelCompositionTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
SSCS-9041  - CCD UI – Validate DWP originating and presenting office for the “Response reviewed” event
> SSCS-9041  - CCD UI – Validate DWP originating and presenting office for the “Response reviewed” event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
> SSCS-9122 dateTimeCaseSentToGaps for case data

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
https://tools.hmcts.net/jira/browse/SSCS-8955
https://tools.hmcts.net/jira/browse/SSCS-8956
> SSCS-8955 and SSCS-8956 Maternity allowance benefit code

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AudioVideoEvidenceDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9221
> SSCS-9221 AV Statement PDF

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9181
> Sscs 9181 admit av evidence with statement

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
Here in this PR we are adding the missing Event Types that are defined in the spreadsheet but have not been defined in the code.
> SSCS-9042 - CCD UI – Validation within the Manage DWP document event

- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
SSCS-9270 - Nullpointer for airlookup
> SSCS-9270 - Nullpointer for airlookup

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/PartyItemList.java
- src/test/java/uk/gov/hmcts/reform/sscs/model/PartyItemListTest.java
https://tools.hmcts.net/jira/browse/SSCS-9151
> SSCS-9151 Issue generic letter to party

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9290
> Sscs 9290 rip1 in bundle

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9182
> SSCS-9182 Statement of evidence as own document type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9290
> SSCS-9290 shouldBundleIncludeDocLink for bundle

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-9222
```
[ ] Yes
[ x] No
```
> SSCS-9222: Select hearing for Upload hearing recording event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelComposition.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelCompositionTest.java
https://tools.hmcts.net/jira/browse/SSCS-9302
> SSCS-9302 Update panel composition for iidb

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingRecording.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingRecordingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsHearingRecordingCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9231
Fields added for upload recording hearing event
```
[ ] Yes
[ x] No
```
> SSCS-9231: Upload hearing recording fields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelComposition.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelCompositionTest.java
https://tools.hmcts.net/jira/browse/SSCS-9302
- Updating the variable name.
```
[ ] Yes
[x] No
```
> Update JUDGE_AND_UP_TO_TWO_CONSULTANT_DOCTORS variable name

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDeprecatedFields.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9305
> SSCS-9305 Panel doctor specialism field and move deprecated fields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingRecording.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingRecordingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsHearingRecording.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsHearingRecordingCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsHearingRecordingDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9233
```
[ ] Yes
[ x] No
```
> SSCS-9233: Upload hearing recordings submit event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/CaseCodeService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CaseCodeServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
added addresses for Social Fund benefit type
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9061](url)
> Sscs 9061 allow social fund

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
SSCS-8924 - Set Benefit Code to 061
SSCS-8925 - Panel List for Notification Content (to Judge)
SSCS-8926 - Airlookup, DWP addresses & Robot Configuration
<div class="user-content-block" style="outline: none !important; margin: 0px; padding: 0px; overflow: initial; color: rgb(23, 43, 77); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; …
> SSCS-8924 - Income Support

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/FormType.java
https://tools.hmcts.net/jira/browse/SSCS-9403
added form
```
[ ] Yes
[x] No
```
> Sscs 9403 add form for new types

- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
add RfE to UC benefit addresses
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9358](url)
> SSCS-9358-add RfE to UC benefit addresses

- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9450
> SSCS-9450 Recovery from Estates dwpRegionalCentre

- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9452
> SSCS-9452 DWP handling office for income support rfe

- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9459
> SSCS-9459 Income support update rfe mappings

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-9449
> SSCS-9449 Remove AV playback workarounds

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/exception/BenefitMappingException.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/CaseCodeService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CaseCodeServiceTest.java
SSCS-9341 BenefitType not found
> SSCS-9341 BenefitType not found

- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
> SSCS-9505: PIP Benefit - PIP DWP addresses marked as 'invalid office'

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)
> SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9502
```
[ ] Yes
[ ] No
```
> SSCS-9502: Change Benefit name from Pension Credits to Pension Credit

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PostponementRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
SSCS-9432 - Postponement request
> SSCS-9432 - Postponement request

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/ScannedDocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PostponementRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
> Revert "SSCS-9433-Adding details to the document so the user can add the reas…"

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PostponementRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ProcessRequestAction.java
https://tools.hmcts.net/jira/browse/SSCS-9438
Action Postponement Request Event - Send to Judge
```
[ ] Yes
[ x] No
```
> Sscs 9438 postponement send to judge

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9601
> SSCS-9601 Child maintenance number

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-9561
Change Event Name from 'Process hearing recording' to 'Action hearing recording req'
```
[ x] Yes
[ ] No
```
> SSCS-9562- change event name

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseService.java
- src/main/java/uk/gov/hmcts/reform/sscs/idam/IdamService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseServiceSpringTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseServiceTest.java
> Spring retry test

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Appellant.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AppellantRole.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Role.java
https://tools.hmcts.net/jira/browse/SSCS-9577
```
[ ] Yes
[ ] No
```
> Sscs-9577: Bulk Scan: SSCS2 Form - Section 1: (YOUR DETAILS) - The Paying/Receiving/Other party fields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelComposition.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelCompositionTest.java
https://tools.hmcts.net/jira/browse/SSCS-9625
> SSCS-9625 Child support panel list

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Appellant.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9565
Bulk Scan: SSCS2 Form - Section 5: (ABOUT CONFIDENTIALITY)
```
[ x] Yes
[ ] No
```
> Sscs 9565 sscs2 form section 5

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsFinalDecisionCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9333
```
[ ] Yes
[x ] No
```
> SSCS-9333: Move related fields to separate class

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9675
> SSCS-9675 Use bundleAddition for av evidence additions

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
SSCS - 9309 - Add withdrawalDocument field to SscsCaseData
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9309](url)
> Sscs 9309 add withdrawal sscs document

- src/main/resources/reference-data/dwpAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupServiceTest.java
> SSCS-9635: SYA – Set default value on creation for dwpRegionalCentre

- src/main/java/uk/gov/hmcts/reform/sscs/model/PartyItemList.java
- src/test/java/uk/gov/hmcts/reform/sscs/model/PartyItemListTest.java
https://tools.hmcts.net/jira/browse/SSCS-9729
> SSCS-9729 Find party item by code

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Appointee.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AudioVideoEvidenceDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OtherParty.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/main/resources/schema/sscs-robotics.json
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidatorTest.java
- src/test/resources/schema/valid_robotics_agreed_multiple_other_parties.json
- src/test/resources/schema/valid_robotics_agreed_single_other_parties.json
https://tools.hmcts.net/jira/browse/SSCS-9755
> Sscs 9755 other party robotics

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
https://tools.hmcts.net/jira/browse/SSCS-9749
Field for test
```
[ ] Yes
[x] No
```
> sscs 9749 added field for testing

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsQueryBuilder.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsQueryBuilderTest.java
SSCS-9801 - login to MYA by an other party
> SSCS-9801 - login to MYA by an other party

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9746
Child Support: Confirm Panel Composition Event
```
[ ] Yes
[x ] No
```
> Sscs 9746 confirm panel composition event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocument.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
> SSCS-9777: Tribunals / Common – Change the document ordering

- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
https://tools.hmcts.net/jira/browse/SSCS-9755
> SSCS-9755 Handle empty reps for SSCS2 cases

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocument.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
Reverts hmcts/sscs-common#1034
> Revert "SSCS-9777: Tribunals / Common – Change the document ordering"

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/PartyItemList.java
- src/test/java/uk/gov/hmcts/reform/sscs/model/PartyItemListTest.java
https://tools.hmcts.net/jira/browse/SSCS-9748
> Sscs 9748 other party hearing preferences

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
https://tools.hmcts.net/jira/browse/SSCS-9862
> SSCS-9862 Add originalSenderOtherPartyId to documents

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/FormType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
https://tools.hmcts.net/jira/browse/SSCS-9779
> SSCS-9779 SSCS5 form type

- README.md
https://tools.hmcts.net/jira/browse/SSCS-9719
```
[ ] Yes
[ x] No
```
> SSCS-9719: Update readme for ccd-definition sync

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Appointee.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OtherParty.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsQueryBuilder.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsQueryBuilderTest.java
https://tools.hmcts.net/jira/browse/SSCS-9735
Add other party subscriptions
```
[ ] Yes
[x] No
```
> sscs 9735 added subscriptions to other party

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OtherParty.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ReasonableAdjustmentsLetters.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/LetterType.java
- src/test/java/uk/gov/hmcts/reform/sscs/model/LetterTypeTest.java
https://tools.hmcts.net/jira/browse/SSCS-9730
Rebased version of #1043
> SSCS-9730 Other party reasonable adjustment

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9730
> SSCS-9730 Show other party details field

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-9882
caseName field
```
[ ] Yes
[x] No
```
> sscs 9882 added caseName

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitTest.java
https://tools.hmcts.net/jira/browse/SSCS-9783
> SSCS-9783 Panel list for SSCS5 benefits

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
SSCS-9927 - Process Reasonable Adjustments for Other Parties
> SSCS-9927 - Process Reasonable Adjustments

- build.gradle
> move jcenter down in the order

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OtherParty.java
https://tools.hmcts.net/jira/browse/SSCS-9842
```
[ ] Yes
[ x] No
```
> SSCS-9842:SSCS5 Update other party data event

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
https://tools.hmcts.net/jira/browse/SSCS-9881
> SSCS-9881 Change PHME to PHE

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseManagementLocation.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/client/RefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CourtVenue.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/RefDataService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RefDataServiceTest.java
> SSCS-9903: Location data – Populate location data on creation SYA and case update

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9961
> SSCS-9961 Set HMCTS Service Id in supplementary data

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkAllocationFields.java
https://tools.hmcts.net/jira/browse/SSCS-9945
New fields fields for WA
```
[ ] Yes
[x] No
```
> sscs 9945 new fields for WA

- src/main/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapper.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-9841
> SSCS-9841 Robotics SSCS5

- src/main/java/uk/gov/hmcts/reform/sscs/model/PartyItemList.java
- src/test/java/uk/gov/hmcts/reform/sscs/model/PartyItemListTest.java
https://tools.hmcts.net/jira/browse/SSCS-9878
> SSCS-9878 bugfix for other party hearing preferences

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/client/CcdClient.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
https://tools.hmcts.net/jira/browse/SSCS-10068
Use new ccd client to set supplementary data
```
[ ] Yes
[x] No
```
> sscs 10068 set supplementary data

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/client/CcdClient.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
Rolling back change causing error
```
[ ] Yes
[X] No
```
> rollback change

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/client/CcdClient.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
https://tools.hmcts.net/jira/browse/SSCS-10068
Integrates with new ccd client
```
[ ] Yes
[x] No
```
> sscs 10068 integrate with new ccd client

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookRcSpreadSheetTest.java
https://tools.hmcts.net/jira/browse/SSCS-10166
poi and opencvs versions are updated as the security vulnerabilities they have are preventing feature developments
```
[X ] Yes
[ ] No
```
> SSCS-10166-Upgrade/Fix poi and commons-beanutils vulnerabilities

- src/main/java/uk/gov/hmcts/reform/sscs/client/CommonReferenceDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseFlag.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/Categories.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/Category.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CategoryRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/Flag.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/FlagDetail.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/ListOfValue.java
https://tools.hmcts.net/jira/browse/SSCS-10219
CommonReferenceDataApi and realted POJO's are added
```
[ ] Yes
[X] No
```
> SSCS-10219-CommonReferenceDataApi initialized

- src/main/java/uk/gov/hmcts/reform/sscs/client/CaseWorkerRefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/client/CaseWorkerRefUsersDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseWorkerDomain.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseWorkerLocationRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseWorkerProfilesDeletionResponse.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseWorkerRoleRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseWorkerWorkAreaRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/CaseWorkersProfileCreationRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/MappingField.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/ServiceRoleMapping.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/UserRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/utility/TrimStringFields.java
- src/test/java/uk/gov/hmcts/reform/sscs/utility/TrimStringFieldsTest.java
https://tools.hmcts.net/jira/browse/SSCS-10218
Added feign client and related model classes for the caseworker reference data
```
[ ] Yes
[x] No
```
> SSCS-10218 Staff reference interface added

- src/main/java/uk/gov/hmcts/reform/sscs/client/JudicialRefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/client/JudicialRefDataRequest.java
> SSCS-10217 added feign client for judicial ref data api search endpoint

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OtherPartyAttendedQuestion.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OtherPartyAttendedQuestionDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsFinalDecisionCaseData.java
> SSCS-9975: SSCS5 - Update Write Final Decision Event

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10318
upgrade org.apache.poi to fix pipelines
```
[ ] Yes
[x ] No
```
> sscs-10318: upgrade org.apache.poi

- src/main/java/uk/gov/hmcts/reform/sscs/client/CaseWorkerRefUsersDataApi.java
sscs 9911
makes the name unique, was getting error in migration tool of duplicate name
```
[ ] Yes
[ ] No
```
> made name unique

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsIndustrialInjuriesData.java
https://tools.hmcts.net/jira/browse/SSCS-10146
Add a second dropdown (secondPanelDoctorSpecialism) that uses the same fixedlist data source and able to view the new field in "Summary", "Appeal details" tab.
```
[ ] Yes
[ ] No
```
> SSCS-10146 Add new varible in SscsCaseData

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10376
```
[ ] Yes
[ ] No
```
> SSCS-10376 Remove springFox and use springDoc

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseAccessManagementFields.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkAllocationFields.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/CaseAccessManagementFieldsTest.java
https://tools.hmcts.net/jira/browse/SSCS-10490
- moved case access management fields into separate class
```
[ x ] Yes
[ ] No
```
> SSCS-10490 moved case access management fields into separate class

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/JointParty.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/sscscasedata/JointPartyIdentityAndAppellantIdentityValidationTest.java
https://tools.hmcts.net/jira/browse/SSCS-10566
Adding JointPartyId to JointParty
```
[ ] Yes
[x ] No
```
> Sscs 10566

- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/mappings/HearingChannel.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/mappings/HearingSubChannel.java
> Sscs 10138 new hearing channel types

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/CancellationReason.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoaderTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
> Sscs 10286 demo pr branch

- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/EntityRoleCode.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingTypeLov.java
> SSCS-10617 Update EntityRoleCode and HearingTypeLoV

- src/main/java/uk/gov/hmcts/reform/sscs/model/hearings/HearingRequest.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/CancellationReason.java
Hearings Cancellation tickets
```
[ ] Yes
[x] No
```
> feat: only cancel hearings related changes

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Hearing.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingStatus.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SchedulingAndListingFields.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> SSCS-10620 qa demo pr

- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoaderTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10517
adding new VenueService method to get venue by postcode
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ x ] No
```
> SSCS-10517 added new VenueService method to get venue by postcode

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/State.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/CancellationReason.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoaderTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10286
```
[ ] Yes
[x] No
```
> SSCS-10286 Critical Data Points For Hearing Journey

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkBasketFields.java
> SSCS-10178 QA Demo Branch

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkBasketFields.java
https://tools.hmcts.net/jira/browse/SSCS-10242
```
[ ] Yes
[ ] No
```
> SSCS-10242 QA Demo Branch

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Hearing.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingStatus.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-10620
```
[ ] Yes
[x] No
```
> SSCS-10620 Update Hearing Information Post Topic

- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingPriority.java
https://tools.hmcts.net/jira/browse/SSCS-10642
```
[ ] Yes
[x] No
```
> SSCS-10642 HearingPriority Reference Data Update

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkBasketFields.java
- src/test/resources/adminAppealWithdrawnCallback.json
- src/test/resources/updateFurtherEvidence.json
https://tools.hmcts.net/jira/browse/SSCS-10242
```
[ ] Yes
[x] No
```
> SSCS-10242 WorkBasketFields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelMember.java
https://tools.hmcts.net/jira/browse/SSCS-10693
```
[ ] Yes
[X] No
```
> SSCS-10693

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkBasketFields.java
- src/main/resources/reference-data/rpc-data.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterServiceTest.java
- src/test/resources/adminAppealWithdrawnCallback.json
- src/test/resources/updateFurtherEvidence.json
https://tools.hmcts.net/jira/browse/SSCS-10178
```
[ ] Yes
[x] No
```
> SSCS-10178 WorkBasketFields

- src/main/resources/reference-data/rpc-data.json
- src/test/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterServiceTest.java
Revert "Temp RPC Update"
```
[ ] Yes
[ ] No
```
> Revert "Temp RPC Update"

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/RegionalProcessingCenter.java
- src/main/resources/reference-data/rpc-data.json
> SSCS-10517 Add epims ids to RPCs.

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AmendReason.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SchedulingAndListingFields.java
https://tools.hmcts.net/jira/browse/SSCS-10598
```
[ ] Yes
[x] No
```
> SSCS-10598 Amending Hearing Request

- src/main/resources/reference-data/rpc-data.json
https://tools.hmcts.net/jira/browse/SSCS-10706
Changing the hearing route for Cardiff RPC to List assist
```
[ ] Yes
[x] No
```
> SSCS-10706-Gaps-Override-release : turn cardiff rpc to LA

- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/CancellationReason.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingChannel.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingSubChannel.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/JudicialMemberType.java
Revert changes
```
[ ] Yes
[X ] No
```
> SSCS-10773: commit revert

- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoaderTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
Reverts hmcts/sscs-common#1266
> Revert "SSCS-10332 - Ability to book hearings for 'paper' cases to any venue within the same region as the RPC"

- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/CancellationReason.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingChannel.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingSubChannel.java
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/JudicialMemberType.java
https://tools.hmcts.net/jira/browse/SSCS-10773
Add toString() to HearingChannel, HearingSubChannel, CancellationReason, JudicialMemberType
```
[ ] Yes
[x ] No
```
> Sscs 10773 fix overridefields

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/AbstractDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ScannedDocument.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/ScannedDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsDocumentDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsWelshDocumentDetails.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/deserialisation/SscsCaseCallbackDeserializerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-9874
```
[ ] Yes
[X] No
```
> SSCS 9874 Control Number

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Interpreter.java
https://tools.hmcts.net/jira/browse/SSCS-10810
Change to common project to facilitate hearings-api updates, which includes creation of Interpreter domain object class.
```
[ ] Yes
[x] No
```
> SSCS-10810 - Don't send relatedParties payload for Appointees, Jp's & Other parties

- src/main/java/uk/gov/hmcts/reform/sscs/client/RefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/RefDataService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RefDataServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
> SSCS-10841 Add epims id resolution.

- src/main/java/uk/gov/hmcts/reform/sscs/client/RefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/RefDataService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RefDataServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
Reverts hmcts/sscs-common#1279
> Revert "SSCS-10841 Add epims id resolution."

- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
SSCS-10823
```
[ ] Yes
[ ] No
```
> added test to check for updatelistingreq in event type

- src/main/java/uk/gov/hmcts/reform/sscs/client/RefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/RefDataService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RefDataServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
Reverts hmcts/sscs-common#1289
> Revert "Feature/sscs 10841 use epims id court venue"

- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoader.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/VenueService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueDataLoaderTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/VenueServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10332
PR previously approved, merged to master accidentally, needs approval again...
```
[ ] Yes
[x] No
```
> SSCS-10332 - Ability to book hearings for 'paper' cases to any venue within the same region as the RPC

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Entity.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Interpreter.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/JointParty.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/util/CaseDataUtils.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdServiceTest.java
- src/test/resources/adminAppealWithdrawnCallback.json
- src/test/resources/updateFurtherEvidence.json
https://tools.hmcts.net/jira/browse/SSCS-10882
```
[x] Yes
[ ] No
```
> SSCS-10882 Fixing Conflicting IDs

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OverrideFields.java
https://tools.hmcts.net/jira/browse/SSCS-10892
```
[ ] Yes
[x] No
```
> SSCS-10892 Remove Reserve to Judge

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
[SSCS-10913](https://tools.hmcts.net/jira/projects/SSCS/issues/SSCS-10913)
- Fix for a side-effect in getLatestHearing
- Dedicated unit-test for getLatestHearing to ensure stability of its sorting criteria
- JavaDoc to clarify the meaning of "latest" in the context of getLatestHearing
```
[ ] Yes
[x] No
```
> SSCS-10913 Fix code with side-effects

- .github/workflows/jitpack_snapshot_commit.yml
> SSCS-11057 Jitpack Snapshot & Commit Build

- .github/sscs-renovate.json
> SSCS-11063 Renovate Update Groups and fix ccd-case-doc version

- .github/sscs-renovate.json
- .github/workflows/renovate_config_tests.yml
> SSCS-11063 Renovate Config Tests

- build.gradle
- config/owasp/suppressions.xml
> Fixing Vulnerabilities

- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
> SSCS-11202 - checkstyle issue fix in AirLookupServiceTest

- build.gradle
- config/git/pre-commit
> Sscs 11165 pre commit hooks

- build.gradle
- config/owasp/suppressions.xml
> SSCS-11249 - upgrade dependencycheck

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
SSCS-11325
https://tools.hmcts.net/jira/browse/SSCS-11325
add an event type of handling_error
```
[ ] Yes
[x] No
```
> add an event type of handling_error

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OverrideFields.java
SSCS-11359
```
[ ] Yes
[ ] No
```
> change override duration to Integer from number

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/model/HearingChannel.java
> New commons branch with HearingChannel change.

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/DocumentType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/callback/ScannedDocumentType.java
https://tools.hmcts.net/jira/browse/SSCS-10539
SSCS-10539 - New Set Aside Application DocumentType and ScannedDocumentType
```
[ ] Yes
[x] No
```
> SSCS-10539 - New Set Aside Application DocumentType and ScannedDocumentType

- build.gradle
- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/callback/CallbackTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/validation/localdate/LocalDateYearMustBeInPastValidatorTest.java
> suppress and upgrade

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Adjournment.java
- src/main/java/uk/gov/hmcts/reform/sscs/utility/StringUtils.java
SSCS-11535
```
[ ] Yes
[ ] No
```
> check for all whitespace and not just one space

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SetAsideActions.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdCallbackMapService.java
https://tools.hmcts.net/jira/browse/SSCS-10543
```
[ ] Yes
[x] No
```
> update interloc state for set aside SSCS-10543

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Adjournment.java
SSCS-10290
```
[ ] Yes
[ ] No
```
> add back old panel members SSCS-11543

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> renovate 23-03-23

- build.gradle
- config/owasp/suppressions.xml
> renovate 23-04-04

- .github/sscs-renovate.json
> SSCS-11563 : Updated renovate settings to auto merge minor PRs

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PostHearing.java
https://tools.hmcts.net/jira/browse/SSCS-10757
adds getRequestFormat method to PostHearing
```
[ ] Yes
[ x ] No
```
> SSCS-10757 adds getRequestFormat method to PostHearing

- .github/sscs-renovate.json
> SSCS-11563 : Remove auto merging for spring and terraform

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DwpState.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SetAsideActions.java
JIRA: https://tools.hmcts.net/jira/browse/SSCS-10544
Added the new Set Aside state details.
```
[ ] Yes
[ X] No
```
> SSCS-10544: Added the Set Aside Grant state

- build.gradle
- src/test/java/uk/gov/hmcts/reform/sscs/service/JudicialRefDataServiceTest.java
> revovate 2023-04-26

- build.gradle
CVEFix.03.05.23
```
[ ] Yes
[x] No
```
> CVEFix.03.05.23

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/InterlocReferralReason.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsFinalDecisionCaseData.java
https://tools.hmcts.net/jira/browse/SSCS-10934
```
[ ] Yes
[ ] No
```
> SSCS-10934 Appointee details when writing a final decision

- config/owasp/suppressions.xml
fix suppressions
```
[ ] Yes
[ ] No
```
> fix suppressions

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventTypeTest.java
…ormation
```
[ ] Yes
[ ] No
```
> SSCS-10973 - rename requestInfoIncompleteApplication to Requestforinformation

- config/owasp/suppressions.xml
SSCS-10587
```
[ ] Yes
[ ] No
```
> suppression fix

- build.gradle
- config/owasp/suppressions.xml
CVE Fix 30.06.2023
```
[ ] Yes
[x] No
```
> CVE Fix 30.06.2023

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/LibertyToApplyActions.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SetAsideActions.java
SSCS-10606
```
[ ] Yes
[ ] No
```
> Common: update actions

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> renovate 2023-07-21

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-11714
Java 17
```
[ ] Yes
[x] No
```
> SSCS-11714 - Java 17

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/WorkAllocationFields.java
https://tools.hmcts.net/jira/browse/SSCS-11873
Added field _daysToHearing_
```
[ ] Yes
[x] No
```
> SSCS-11873 Added field daysToHearing

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/JudicialUserPanel.java
SSCS-11339
```
[ ] Yes
[ ] No
```
> Common: add back judicial user panel

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
> Common: add annotations to localDate

- config/owasp/suppressions.xml
> Add Suppressions

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PermissionToAppealActions.java
> Commons: update interloc strate change to review by judge

- src/main/java/uk/gov/hmcts/reform/sscs/client/JudicialRefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/JudicialRefDataService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/JudicialRefDataServiceTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-579
Add elinks feature flag to each env
> SSCSCI-579 - Elinks feature toggling

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/AirLookupServiceTest.java
> Common: add get for venueid from venue name

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/InterlocReferralReason.java
https://tools.hmcts.net/jira/browse/SSCS-12337
Add additional interloc referral reasons
> SSCS-12337 Fix referred to interloc judge task

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsFinalDecisionCaseData.java
- src/main/java/uk/gov/hmcts/reform/sscs/client/JudicialRefDataApi.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/client/JudicialMemberAuthorisations.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/client/JudicialUser.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/JudicialRefDataService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/JudicialRefDataServiceTest.java
checkstyle fixes
https://tools.hmcts.net/jira/browse/SSCS-12116
Changed logic of how full name of judicial user is generated
> Changed logic of how full name of judicial user is generated

- config/owasp/suppressions.xml
> SSCSCI - Update Suppressions

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
https://tools.hmcts.net/jira/browse/SSCSSI-90
> SSCSSI-90 Add triggerCaseEvent to UpdateCcdCaseService

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
This reverts commit b449c7aa5cfc81b1fbb856e5a0a5ab50ed5c3a46.
Reverting till testing in preview is fully conducted
> Revert "updateCaseV2 passes SscsCaseDetails (#1580)"

- jitpack.yml
> SSCSSI-jitpack-JDK17: updated

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-957
Dependency check bump to latest version (10.0.3)
Suppression date update
PMD reports folder fix
> SSCSCI-957 dependency check bump

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCSCI-954
> Introduce new field to determine if warnings needs to be ignored when triggering event from submitted handler

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Address.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Identity.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/UkPortOfEntry.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/AddressTest.java
See [SSCSCI-1123](https://tools.hmcts.net/jira/browse/SSCSCI-1123)
> Sscsci 1123 is uk address, country and port of entry addition

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Address.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Identity.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/AddressTest.java
See [SSCSCI-1123](https://tools.hmcts.net/jira/browse/SSCSCI-1123)
Providing a test for the failing test in tribunals api based on the new fields not matching the expected JSON
> Sscsci 1123 new Address and identity fields fix

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Address.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Party.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/AirLookupService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/AddressTest.java
- src/test/resources/adminAppealWithdrawnCallback.json
- src/test/resources/updateFurtherEvidence.json
https://tools.hmcts.net/jira/browse/SSCSCI-1128
Make changes to commons lib to facilitate manual case creation
> SSCSCI-1128

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Address.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Party.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/AddressTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RegionalProcessingCenterServiceTest.java
See [SSCSCI-1179](https://tools.hmcts.net/jira/browse/SSCSCI-1179)
> SSCSCI-1179 required changes

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> updating Infected Blood Appeal to Infected Blood Compensation

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/UpdateCcdCaseService.java
See [SSCSCI-1358](https://tools.hmcts.net/jira/browse/SSCSCI-1358)
Added RuntimeException to update case recover method to resolve caseloader test failure
> SSCSCI-1358 Added RuntimeException to recover method

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingOutcome.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingOutcomeDetails.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingOutcomeValue.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
See [SSCSCI-1189](https://tools.hmcts.net/jira/browse/SSCSCI-1189)
Added new objects for Hearing Outcome feature:
- HearingOutcome: collection of HearingOutcomeDetails
- HearingOutcomeDetails: complex type that holds details that need to be saved and displayed
- HearingOutcomeValue: complex type needed to temporarily store values when creating a new hearing outcome
> SSCSCI-1189 database structure for hearing outcome

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/model/dwp/DwpMappings.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/DwpAddressLookupService.java
- src/main/resources/reference-data/ftaAddresses.json
- src/test/java/uk/gov/hmcts/reform/sscs/robotics/RoboticsJsonMapperTest.java
replacing all instances of infected blood appeal with infected blood compensation
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> IBA name alteration

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/BenefitType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseDataTest.java
See [SSCSCI-1406](https://tools.hmcts.net/jira/browse/SSCSCI-1406)
Adding an 'isIbcCase' method so be used in tribunals API to consolidate the use of 'isIba' methods created
> SSCSCI-1406: BenefitType update to consolidate ibc code in tribunals

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/DirectionType.java
See [SSCSCI-1345](https://tools.hmcts.net/jira/browse/SSCSCI-1345)
> SSCSCI-1345 adding new direction type

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/Benefit.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
https://tools.hmcts.net/jira/browse/SSCSCI-1206
Add new case fields required for ibca in the dwpUploadResponse event
> SSCSCI-1206

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/EventType.java
https://tools.hmcts.net/jira/browse/SSCSCI-1444
> Added new event type remove case outcome for superusers

- src/main/resources/reference-data/session-category-map.json
See [SSCSCI-1439](https://tools.hmcts.net/jira/browse/SSCSCI-1439)
adding SD to IBC valid issue codes
> SSCSCI-1439

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HearingOptions.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/HmcHearingType.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/OverrideFields.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/domain/HmcHearingTypeTest.java
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> SSCSCI-1456

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/CcdService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseService.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertService.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SearchCcdCaseServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/ccd/service/SscsCcdConvertServiceTest.java
- See [SSCSCI-1747](https://tools.hmcts.net/jira/browse/SSCSCI-1747)
- enable searching for non submitted cases
> SSCSCI-1747: enable searching for non submitted cases

- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/PanelMemberComposition.java
- src/main/java/uk/gov/hmcts/reform/sscs/ccd/domain/SscsCaseData.java
See [SSCSCI-1186](https://tools.hmcts.net/jira/browse/SSCSCI-1186)
Add panel member composition object to case data
> SSCSCI-1186 add PanelMemberComposition object

- README.md
See [SSCSCI-1789](https://tools.hmcts.net/jira/browse/SSCSCI-1789)
Readme update
> SSCSCI: Updated readme

- src/main/java/uk/gov/hmcts/reform/sscs/reference/data/service/PanelCompositionService.java
- src/test/java/uk/gov/hmcts/reform/sscs/reference/data/service/PanelCompositionServiceTest.java
See [SSCSCI-1571](https://tools.hmcts.net/jira/browse/SSCSCI-1571)
Get role types even if null
> Sscsci 1571 Submit ULR
